puts ">> Loading models..."
require File.join(File.dirname(__FILE__),"time_date")
require File.join(File.dirname(__FILE__), "generated_model/LifeForce")
require File.join(File.dirname(__FILE__),"lifeforce")
require File.join(File.dirname(__FILE__),"member")
require File.join(File.dirname(__FILE__),"show")
require File.join(File.dirname(__FILE__),"episode")
require File.join(File.dirname(__FILE__),"video")
require File.join(File.dirname(__FILE__),"showcase")
require File.join(File.dirname(__FILE__),"sys_message")
require File.join(File.dirname(__FILE__),"note")
require File.join(File.dirname(__FILE__),"description")
require File.join(File.dirname(__FILE__),"genera")
require File.join(File.dirname(__FILE__),"related-show")
require File.join(File.dirname(__FILE__),"resource")
require File.join(File.dirname(__FILE__),"season")
require File.join(File.dirname(__FILE__),"search")
require File.join(File.dirname(__FILE__),"adsense")
require File.join(File.dirname(__FILE__),"analytics")
require File.join(File.dirname(__FILE__),"credit")
puts ">> done loading models"
